---
title: "Debug Notebook for NBodyPropagatorNBodyPropagator.jl" \
author: "Naoya Ozaki" \
date: "31 January 2023" \
output: "nbp_debug"

---

In [ ]:
struct TestA
    a ::Float64
    b ::Array{Float64,1}

    TestA(a=0.2, b=[1.1, 2.2]) = new(a,b)
end

testA = TestA()
println(testA)

testA = TestA(0.4)
println(testA)

testA = TestA(0.4, [3.3, 4.4])
println(testA)

In [1]:
using NBodyPropagator

et0 = 0.0
x0 = [1e7, 1e8, 1e6, 15, 20, 3]
tspan = (et0, et0 + 30 * 86400)

nbp = NBodyProblem(x0, tspan, [10, 399, 301]; id_center=10, need_stm=false)
sol = propagate(nbp)

6×19 Matrix{Float64}:
  1.0e7   1.02952e7   1.11598e7  …   3.95116e7   4.18889e7   4.24735e7
  1.0e8   1.00391e8   1.01513e8      1.18469e8   1.17739e8   1.17478e8
  1.0e6   1.05906e6   1.23236e6      7.14326e6   7.66372e6   7.79266e6
 15.0    14.974      14.8953        10.2737      9.61547     9.44038
 20.0    19.7437     19.0025        -2.09743    -4.00754    -4.49572
  3.0     2.99737     2.98896    …   2.23702     2.11728     2.0852

In [3]:
Avec = [1, 2, 3, 4];
Amat = reshape(Avec, (2, 2))
vec(Amat)

4-element Vector{Int64}:
 1
 2
 3
 4

In [4]:
zeros(6,6)

6×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [7]:
if true
    dfdr = zeros(3, 3)
    dfdt0 = zeros(3)
end

dfdt0

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [18]:
using LinearAlgebra
dfdx = [
    zeros(3, 3) Matrix{Float64}(I, 3, 3);
    rand(3, 3) zeros(3, 3)
    ]

6×6 Matrix{Float64}:
 0.0       0.0        0.0        1.0  0.0  0.0
 0.0       0.0        0.0        0.0  1.0  0.0
 0.0       0.0        0.0        0.0  0.0  1.0
 0.278246  0.246698   0.0232303  0.0  0.0  0.0
 0.927954  0.324193   0.74263    0.0  0.0  0.0
 0.506926  0.0341329  0.133334   0.0  0.0  0.0

In [22]:
dfdx * dfdx'

6×6 Matrix{Float64}:
 1.0  0.0  0.0  0.0       0.0       0.0
 0.0  1.0  0.0  0.0       0.0       0.0
 0.0  0.0  1.0  0.0       0.0       0.0
 0.0  0.0  0.0  0.13882   0.355429  0.152568
 0.0  0.0  0.0  0.355429  1.5177    0.580488
 0.0  0.0  0.0  0.152568  0.580488  0.275917